__path = process.cwd()
module.exports = async (md, m, fetchJson, bot, type, body, budy, prefix, isCommand, command, isGroup, md1, pushname, q, args, content, sender, from, nama, namabot, owner, reply, donasi, isMedia, isQuotedImage, isQuotedVideo, isQuotedSticker, isQuotedAudio) => {  
try{  

var gombal = [
"Aku tak pernah berjanji untuk sebuah perasaan, namun aku berusaha berjanji untuk sebuah kesetiaan.",
"Jangankan memilikimu, mendengar kamu kentut aja aku sudah bahagia.",
"Berulang tahun memang indah, namun bagiku yang lebih indah jika berulang kali bersamamu.",
"Kesasar itu serasa rugi banget, namun aku nggak merasa rugi karena cintaku sudah kesasar ke hatimu.",
"Ada 3 hal yang paling aku sukai di dunia ini, yaitu matahari, bulan dan kamu. Matahari untuk siang hari, bulan untuk malam hari, dan kamu untuk selamanya di hatiku.",
"Aku tidak peduli ramalan BMKG, sebab saat hujan, badai bahkan tsunami aku akan tetap bertahan pada cintamu.",
"Kamu itu seperti garam di lautan, tidak terlihat namun akan selalu ada untuk selamanya.",
"Makna dari rumus e = m . c^2 yaitu [engkau = manis . cantiknya emang 'kodrat' mu., Hidupku tanpamu bagaikan cos90 = 0. Kau dan aku adalah sin90 = 1 dan selalu bersamamu adalah tan90 = tak terhingga.",
"Kalau kamu adalah bumi, maka aku adalah atmosfernya. Dengan begitu setiap saat bisa melindungimu dari sakitnya serangan meteor dan komet.",
"Cintaku padamu seperti ban kereta api, tidak pernah kempes.",
"Aku rela dipenjara asalkan pelanggarannya karena mencintaimu.",
"Aku ingin kita seperti sandal jepit sebab hanya ada dua, tidak ada yang namanya orang ketiga.",
"Tuhan itu baik yah. Saat aku minta bunga mawar, aku diberi taman yang indah. Saat aku meminta setetes air, aku diberi lautan. Eh, saat aku minta malaikat, aku diberi kamu.",
"Jika kau memegang 7 bunga mawar di depan cermin, maka kau adalah mawar ke-8 yang terindah di seluruh dunia.",
"Kamu memang seperti lempeng bumi, bergeser sedikit saja sudah mengguncang hatiku.",
"Kata dimulai dengan ABC, angka dimulai dengan 123. Lagu dimulai dengan do re mi. Cinta dimulai dengan aku dan kamu.",
"Ada 12 bulan dalam setahun, 30 hari dalam sebulan, 7 hari dalam seminggu, 60 detik dalam satu jam. Tapi hanya ada kamu seorang sepanjang hidupku.",
"Kutuliskan namamu di langit, angin meniupnya. Kutuliskan namamu di laut, badai membawanya. Kutuliskan namamu di hatiku, cinta namanya.",
"Titik koma dalam sebuah kalimat saja kuperhatikan, apalagi dirimu.",
"Sejak mengenalmu bawaannya aku pengen belajar terus, belajar menjadi yang terbaik buat kamu.",
"Selain tanggal merah yang aku cari di kalender, tapi juga tanggal yang tepat untuk melamar kamu.",
"Napas aku kok sesek banget ya? Karena separuh napasku ada di kamu.",
"Aku mohon jangan jalan-jalan terus di pikiranku, duduk yang manis di hatiku saja.",
"Sayang, tadi pagi aku gak bisa makan karena merindukanmu. Siangnya juga nggak makan karena mikirin kamu. Dan malamnya aku juga nggak bisa tidur karena kelaparan.",
"Kalau hitungan satu sampai sepuluh, cintaku cukup nomor dua, yaitu dualem banget.",
"Jepang bikin robot. Jerman bikin mobil. Kamu bikin kangen.",
"Tanggal merah sekalipun aku tidak libur untuk memikirkan kamu.",
"Aku rela jadi abang nasi goreng asalkan setiap malam aku bisa lewat depan rumah kamu.",
"Handphone saja sanggup simpan foto sampai beribu-ribu, masa hanya untuk menyimpan aku, hati kamu nggak sanggup sih.",
"Walaupun jarak kita bagai Matahari dan Pluto saat ephehelium. Amplitudo gelombang hatimu berintervensi dengan hatiku.",
"Orang kurus itu setia, tambah makan aja tidak pernah tambah apalagi pasangan.",
"Jus, jus apa yang gak pernah manis? Just friend with you.",
"Sejak mengenalmu, bawaannya aku pengen belajar terus. Belajar menjadi yang terbaik buat kamu.",
"Kau memang bukan yang pertama, tapi aku yakin kau adalah yang terakhir untukku.",
"Kamu adalah terang yang akan selalu menyinari hatiku. Tanpamu hidupku kosong dan tidak ada apa-apanya.",
"Apa bedanya tanggal 28 sama 29 Oktober? 28 Oktober itu Sumpah Pemuda kalau 29 Oktober sumpah aku sayang kamu.",
"Apa bedanya cincin sama kamu? Kalau cincin melekat di jari, kalau kamu melekat di hati aku.",
"Apa bedanya kamu dengan jarum jam? Kalau jarum jam muterin angka. Kalau kamu muterin pikiran aku terus.",
"Kalau aku jadi wakil rakyat sepertinya aku bakal gagal, deh. Gimana aku mikirin rakyat, kalau yang ada di pikiranku hanyalah kamu.",
"Kamu tau nggak kenapa kalau aku menghafal sesuatu lihatnya ke atas? Soalnya kalau merem langsung kebayang wajahmu.",
"Malam apa yang paling indah? Melamar kamu.",
"Belajar apa yang paling aku suka? Belajar mencintaimu setulusnya.",
"Kuda, kuda apa yang bikin seneng? Kudapat pacar sepertimu.",
"Aku gak sedih kok kalo besok hari Senin. Aku sedihnya kalau gak ketemu kamu.",
"Tanganmu keliatannya berat, sini aku pegangin.",
"Semua orang perlunya uang, tapi kok aku perlunya kamu ya.",
"Gakpapa namamu panjang, nanti aku juga manggilnya sayang.",
"Kopi, kopi apa yang paling manis? Kopinang kau dengan bismillah.",
"Kos apa yang paling bikin betah? Bikos I love you.",
"Apa bedanya kulkas sama kamu? Kalau kulkas ngedinginin, kalau kamu nganenin.",
"Apa bedanya kamu dan barista? Barista mengaduk-aduk kopi susu, kalau kamu mengaduk-aduk hatiku.",
"Nama kamu Dewi? Dewinner of my heart.",
"Aku dan kamu itu bagaikan laptopku dan wifi cafe depan rumah, udah auto-connect.",
"Selain cuci tangan, kamu tuh harus sering-sering cuci kaki kamu tahu. Soalnya kan telapak kaki kamu akan jadi surga bagi anak-anak kita nanti.",
"Keluar dari rumah memang tidak dianjurkan, tapi yang benar-benar tidak bisa kamu lakukan itu keluar dari pikiranku.",
"Kangen kamu tuh kayak pas balon hijau meledak. Bikin hatiku sangat kacau.",
"Halo, namaku Dion, Dionly man for you.",
"Kamu pasti nanti di masa depan suka nasi deh, nasihatin anak kita berdua.",
"Kipas apa yang aku tunggu? Kipastian dari kamu.",
"Cintaku ke kamu tuh kaya WA hoax dari emak-emak, gak ada habisnya.",
"Mie apa yang lebih nyenengin daripada Indomie? Mielikin kamu.",
"Semoga kita semua dijauhkan dari virus dan didekatkan dengan yang serius.",
"Kamu tuh kaya delman di kota pada hari minggu, istimewa.",
"Selamat, kamu menang penghargaan cerita terbaik. Sejak ada kamu, cerita hidupku menjadi indah.",
"Kotak apa yang menyakitkan? Ko tak sadar ku mencintaimu.",
"Hati-hati kemakan ombak, kamu cukup kemakan rayuanku aja.",
"Kamu itu pensil warna ya? Soalnya kamu mewarnai hari-hariku.",
"Apa bedanya matahari sama kamu? Matahari menyinari bumi, kalau kamu menyinari hatiku.",
"Kalau kamu itu upil, aku adalah jari kelingking. Mencari kamu sampai dapat.",
"Ibu kota boleh pindah ke Kalimantan, asalkan kamu jangan pindah ke hati mantan.",
"Apa perbedaan bendera dan kamu? Bendera berkibar di tiang, kalau kamu berkibar di hatiku.",
"Nama saya Jaelani, nama panjangnya jaelani aja dulu, siapa tau nyaman.",
"Berbagi santap sama kamu aja aku senang, apalagi berbagi atap.",
"Kue apa yang paling membahagiakan? Kuepastian.",
"Kamu orang Jawa ya? Karena kamulah jawaban doaku.",
"Apa bedanya kamu dan polisi lalu lintas? Polantas mengalihkan lalu lintas, kalau kamu mengalihkan duniaku.",
"Apa bedanya Bali sama kamu? Kalau Bali itu tujuan wisata, kalau kamu itu tujuan hidupku.",
"Kamu itu kaya lampu merah, membuatku berhenti ketika melihatnya.",
"Selamanya adalah waktu yang lama. Tapi aku gak keberatan untuk menghabiskan semua itu dengan berada di sisimu.",
"Kalau ada lampu, jangan cari lilin. Kalau ada aku, jangan cari yang lain.",
"Apa singkatan dari STNK? STNK adalah Surat Izin Nikahin Kamu.",
"Coba deh kamu merem 5 detik. Gelap kan? Begitulah kalau aku hidup tanpamu, gelap.",
"Anjing menggonggong, kafilah berlalu. Tiap hari bengong mikirin kamu melulu.",
"Salep, salep apa yang bikin galau? Salepas kau pergi dari sisiku.",
"Kamu itu seperti kado, bisa bikin orang suka dan bahagia.",
"Kok kamu kaya kamera sih? Soalnya kalau liat kamu, aku auto senyum.",
"Aku gak takut nilai ujianku kecil. Aku cuma takut nilai diriku kecil di matamu.",
"Kamu cantiknya kaya e-KTP deh. Soalnya cantiknya seumur hidup.",
"Dari banyaknya menu di restoran, cuma 1 menu yang aku mau, yaitu menua bersamamu.",
"Jika langit punya pelangi untuk dibanggakan, aku punya kamu untuk diperjuangkan.",
"Pasien yang terkena gejala rindu dilarikan ke mana? Ke ruang I See U.",
"Sore membutuhkan senja untuk menambah keindahannya. Aku juga butuh kamu untuk kelengkapi hidupku.",
"Rasa sayangku ke kamu kaya power rangers pas gak ketemu monster, gak bakal berubah.",
"Aku tahu kita gak seumur, tapi bolehkan kalau aku seumur hidup sama kamu?",
"Aku selalu takut menyapamu, bukan karena aku tak berani, tapi karena aku lebih suka mendoakanmu.",
"Kamu tau bedanya cicak sama kamu? Kalau cicak diam-diam merayap, kalau kamu diam-diam aku cinta.",
"Bapak kamu kerja di operator sellular ya? Soalnya sinyal cinta kamu begitu kuat di hatiku.",
"Apa bedanya Borobudur sama kamu? Kalau Borobudur itu candi, kalau kamu itu candu.",
"Makanan yang paling melambangkan perasaanku ke kamu itu gudeg. Gu deg-degan kalau ketemu kamu.",
"Aku orangnya penasaran, tapi ada satu pertanyaan yang aku gak mau tahu jawabannya. Pertanyaannya, bagaimanakah hidupku tanpa kamu?",
"Kata orang, kebutuhan primer manusia itu ada tiga, yaitu sandang, pangan, dan papan. Kalau aku beda, kebutuhan primerku cuma kamu, kamu, dan kamu.",
"Matahari, bintang, dan kamu itu ada kesamaannya lho. Matahari untuk siang hari, bintang untuk malam hari, dan kamu untuk selamanya.",
"Kalau hotel pemandangan pantai, namanya beach view. Kalau pemandangan kota, namanya city view. Kalau pemandangannya kamu, jadinya I loview.",
"Kamu jangan sampai tenggelam di pantai, cukup tenggelam di hatiku aja.",
"Negara Swiss bikin jam, Jerman bikin mobil, kalau kamu bikin kangen.",
"Jangan sebut aku mantan, sebut saja aku alumni, biar kita bisa reuni.",
"Apa persamaanmu sama ujian nasional? Sama-sama gak cukup dipikirin dalam 2 jam.",
"Hemat tiket pesawat deh kalau sama kamu. Soalnya tinggal denger kamu bilang I love you aja udah bisa bikin aku melayang."
]   

md.sendMessage(from, { text: gombal[Math.floor(Math.random() * gombal.length)], mentions: [sender]}, {quoted: md1})
} catch (e) { console.log(e) }
} 
